language: python
sudo: false
python:
    - "2.7"
cache:
  directories:
    - "$HOME/.pip-cache/"
    - "/home/travis/virtualenv/python2.7"
install: 
    - "pip install -r python_requirement.txt  --download-cache $HOME/.pip-cache"
    - "pip install python-coveralls"
    - "pip install coverage"
    - "pip install flake8"
before_script:
    - "flake8 RoboCop.py"
    - git config --global user.email "olxboss@gmail.com"
    - git config --global user.name "Travis-CI"
script:
    - "coverage run -m unittest discover"
after_success:
    - "coverage report"
    - "coveralls"
